name: Upload on AWS S3

on:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: "client"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install Dependencies
        run: npm install

      - name: create build
        run: npm run build

      - name: AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.ACCESS_KEY}}
          aws-secret-access-key: ${{secrets.SECRET_ACCESS_KEY}}
          aws-region: us-east-1

      - name: Upload to S3
        run: aws s3 sync ./build s3://cyf-video-hub --delete
